### ISSUE TITLE
Gmail Support

### ISSUE THREAD

**Issue by Rambou** [TheFox/keylogger#1]
Maybe you could add a gmail support. Sending an email with logs to specific gmail account at a specific amount of time.

**Comment by TheFox** [comment]
_Write programs that do one thing and do it well._ ;)
I don't know if a keylogger really should send emails.

And in the case it sends emails it couldn't send it directly to Gmail because of spam filters. So you must also provide a SMTP server with login credentials. And maybe you also would like to zip the log files before sending them via email.

Beside the option of a specific amount of time I also would provide a specific log file size.

**Comment by Rambou** [comment]
Maybe you right. :+1: Although the way keylogger send Logs is based on the security enviroment. So i don't think that mail support in general, shoudn't be used.
