### ISSUE TITLE
UAC 

### ISSUE THREAD

**Issue by champix** [TheFox/keylogger#5]
input is not captured on UAC prompt

**Comment by TheFox** [comment]
Why not?

**Comment by champix** [comment]
Hi !

Thank you for your quick answer.

I don't know why input is not captured but let me explain what happens :

I compiled the keylogger and ran it, so far everything runs as expected.
FYI it runs on a low privilege user session.

At this point, everything i type is properly logged.

Whenever i try to run an application that requires elevated privileges, let's say for example "C:\Windows\System32\services.msc", i get a UAC prompt asking for Admin password.

As soon as the UAC prompy is displayed, the logging stops, nothing I type will be recorded by the keylogger.

As soon as the UAC prompt is closed, logging starts again like nothing ever happened.


My problem is the following : i want to know what was typed into that UAC prompt


Thanks in advance

**Comment by TheFox** [comment]
I don't know what's going on. But I guess the Windows is disabling the keylogger functions for the password prompt to secure the admin password.

**Comment by miha-x86** [comment]
What happens here is that when the UAC prompt is displayed the desktop is switched to the Secure Desktop where a screenshot of the Default desktop is taken dimmed and shown on the background and then the UAC prompt is created there isolated. Since this desktop is running on the same session as the user maybe it's still possible to capture it without having to elevate your program privileges.
